site_name: ipatel
repo_url: https://github.com/Chethanpatel/ipatel
site_url: https://Chethanpatel.github.io/ipatel/
docs_dir: docs
theme:
  name: readthedocs
  user_color_mode_toggle: true
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - content.code.copy
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true


nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - CLI Usage: cli.md
  - Python API Reference: api.md